name: Lint Ruby

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install RuboCop
        run: |
          gem install rubocop
      - name: Run RuboCop
        run: |
          rubocop -c .rubocop.yml
